const api = require('../connectors/api-client');

async function createBrief() {
  console.log('📋 Creating campaign brief in Asana...\n');
  
  // Get workspace
  const me = await api.asana.getMe();
  const workspaceId = me.data.workspaces[0].gid;
  console.log('Workspace:', me.data.workspaces[0].name);
  
  // Get project to add task to
  const projects = await api.asana.listProjects(workspaceId);
  const project = projects.data[0];
  console.log('Project:', project.name);
  
  // Create the campaign brief
  const briefNotes = `## Campaign Brief

**Client:** Acme Corp
**Product:** Smart Widget Pro
**Campaign Type:** Product Launch

---

### Objectives
- Drive awareness among tech enthusiasts 25-45
- Generate 50,000 site visits
- Achieve 2.5% CTR benchmark

### Budget
- **Total:** $150,000
- **Flight:** Feb 15 - Mar 31, 2026
- **DSPs:** TTD (60%), DV360 (40%)

### Channels
| Channel | Budget | KPI |
|---------|--------|-----|
| CTV | $60K | VCR 85%+ |
| OLV | $45K | VCR 70%+ |
| Display | $30K | CTR 0.15%+ |
| Native | $15K | CTR 0.3%+ |

### Targeting
- **Geo:** US (focus: CA, NY, TX, FL)
- **Demo:** A25-45, HHI $75K+
- **Interests:** Technology, Smart Home, Gadgets
- **Behavioral:** In-market for electronics

### Creative Assets Needed
- [ ] CTV 30s spot (1920x1080)
- [ ] CTV 15s spot (1920x1080)
- [ ] Pre-roll 15s (1920x1080)
- [ ] Display 300x250, 728x90, 160x600
- [ ] Native 1200x628 + headlines

### Timeline
- **Feb 10:** Creative due
- **Feb 12:** Campaign setup in DSPs
- **Feb 14:** QA & trafficking
- **Feb 15:** Launch 🚀

---
*Generated by Ad Ops Command Center*`;

  const brief = await api.asana.createTask({
    workspace: workspaceId,
    projects: [project.gid],
    name: '🚀 Q1 Product Launch - Programmatic Media Plan',
    notes: briefNotes,
    due_on: '2026-02-10'
  });
  
  console.log('\n✅ Created task:', brief.data.name);
  console.log('   GID:', brief.data.gid);
  console.log('   Due:', brief.data.due_on);
  
  // Add a comment
  const comment = await api.asana.addComment(
    brief.data.gid,
    '🤖 Campaign brief created by Ad Ops Command Center. Ready for review!'
  );
  console.log('\n💬 Added comment');
  
  console.log('\n🔗 Open Asana to see your new campaign brief!');
}

createBrief().catch(e => console.error('Error:', e));
